add test for test-logging-tx-observer
hyperledger-caliper/caliper pull request #1630
Opened 2024-09-11 09:26 UTC by tunedev

## Checklist
 - [ ]  A link to the issue/user story that the pull request relates to
 - [ ]  How to recreate the problem without the fix
 - [ ]  Design of the fix
 - [ ]  How to prove that the fix works
 - [ ]  Automated tests that prove the fix keeps on working
 - [ ]  Documentation - any JSDoc, website, or Stackoverflow answers?

## Issue/User story

Partially addresses #1606

## Steps to Reproduce

1.
2.
3.
4.

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-caliper)
- [x] [GitHub Issues](https://github.com/hyperledger/caliper/issues)
- [ ] [Discord history](https://discord.com/channels/905194001349627914/941417677778473031)

## Design of the fix

## Validation of the fix

After this PR: Running the tests in caliper-core the listed %stmts in the code coverage report should tally with the below listed

- caliper-core/lib/worker/tx-observers/logging-tx-observer.js: 100

Before the PR: Running the tests in caliper-core the listed %stmts in the code coverage report the below listed was what was there before

- caliper-core/lib/worker/tx-observers/logging-tx-observer.js: 0

## Automated Tests

## What documentation has been provided for this pull request

2024-09-15 08:40 UTC, davidkel requested changes
Sorry, needs a few changes here. It also breaks the build (see the build details in the PR and github actions). Please run the unit and integration tests before submitting the PR to avoid this

2024-09-15 08:40 UTC, davidkel commented on packages/caliper-core/test/worker/tx-observers/logging-tx-observer.js
> +        it('should set up the logger with default settings if no options are provided', () => {
Don't think this test proves anything as the logger will always exist

2024-10-10 07:38 UTC, davidkel requested changes
One last change

2024-10-10 10:20 UTC, tunedev commented
true, would remove it now

On Thu, 10 Oct 2024 at 08:38, Dave Kelsey ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> One last change
> ------------------------------
>
> In packages/caliper-core/test/worker/tx-observers/logging-tx-observer.js
> <https://github.com/hyperledger/caliper/pull/1630#discussion_r1792267496>:
>
> > +        logStub = CaliperUtils.getLogger().info;
> +        observer = createLoggingTxObserver({ messageLevel: 'info' }, null, 0);
> +    });
> +
> +    afterEach(() => {
> +        sinon.restore();
> +        logStub.resetHistory();
> +    });
> +
> +    after(() => {
> +        mockery.deregisterAll();
> +        mockery.disable();
> +    });
> +
> +    describe('On initialization', () => {
> +        it('should set up the logger with default settings if no options are provided', () => {
>
> You need to change this test, logStubs.info will always exist because you
> create it in the test. So the test doesn't actually prove anything
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hyperledger/caliper/pull/1630#pullrequestreview-2355135853>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH6TKS2NBGHBEFK76BB3YXDZ2YVHXAVCNFSM6AAAAABOAQ4Z5WVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNJVGEZTKOBVGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-11-06 10:58 UTC, davidkel approved these changes
LGTM

2024-11-06 11:01 UTC, merged